### ISSUE TITLE
Building client with Docker "recipe"

### ISSUE THREAD

**Issue by cedric2080** [alice-lg/alice-lg#102]
Hi,

I am trying to build the client (5.1.1) using the docker image (docker is running in a Debian 11 VM, but I guess it is independant fact), following the instructions:
```
cd client/
make -f Makefile.docker client_prod
```
All I can get is this output:
```
Building alice UI (production)
docker run --rm -t -i -a stdin -a stdout -a stderr -v `pwd`:/client/ --name alice-lg-node-build alice-lg-node:latest /bin/bash -c "DISABLE_LOGGING=1 NODE_ENV=production ./node_modules/.bin/gulp"
internal/modules/cjs/loader.js:857
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /client/node_modules/node-sass/vendor/linux-x64-67/binding.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:857:18)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at module.exports (/client/node_modules/node-sass/lib/binding.js:19:10)
    at Object.<anonymous> (/client/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
make: *** [Makefile.docker:26: client_prod] Error 1
```

What am I missing ?

**Comment by cedric2080** [comment]
Not needed anymore with upcoming v6.0.0.
Thanks.
