### ISSUE TITLE
Another problem with front page search bar

### ISSUE THREAD

**Issue by heaveaxy** [alice-lg/alice-lg#133]
Hi,
When start typing prefix name and type a dot `.` page becomes blank. In browser's development console appears following error (see screen). This occurs only when typing some prefixes.

![Screenshot_20240205_191653](https://github.com/alice-lg/alice-lg/assets/24751685/dcd53aae-8fd0-445e-b30a-4bf734aeb823)

I investigated this issue and found that `211609` is community number. It appears in json data structure of some routes on following path:
`imported.routes[...].bgp.large_communities`. If I start type any prefix in search bar and this part is equal to prefix that have `211609` community, entire page will fail .

**Comment by annikahannig** [comment]
Interesting. Need to check this out. 

Does this also happen in the current development branch?

**Comment by heaveaxy** [comment]
In develop branch this form is not working. Searching any prefix returns following message:
```
The query took too long to process.
Unfortunately, it looks like the query matches a lot of routes.
Please try to refine your query to be more specific.
```
Searching of non-existent prefix return "No routes matching your query".

Backend returns HTTP 502. Alice-lg logs contains a lot of stacktraces.

**Comment by annikahannig** [comment]
Can you maybe attach some of these stack traces?

**Comment by heaveaxy** [comment]
I prepared deploy of devel branch quikly in production env to test only one thing, so I can't repeat this yet. Maybe later.
I can try to gather some info if needed from current deploy from main branch.

**Comment by annikahannig** [comment]
There is actually a release coming up in the next couple of days, so this won't be much helpful. Main now differs substantially from develop.

**Comment by heaveaxy** [comment]
So, after update I unable to check this issue because of another problem. When typing network in search bar it shows the message "The query took too long to process".
In debug console I see query to `https://lg.name.tld/api/v1/lookup/prefix?q=1.2.3.0&page_filtered=0&page_imported=0
` with HTTP response 502.
In log of Alice LG container following error occured:
```
2024/04/15 18:24:22 http: panic serving 10.0.1.3:53116: interface conversion: interface {} is float64, not int
goroutine 5715585 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1868 +0xb9
panic({0xb7d300?, 0xc00093d050?})
        /usr/local/go/src/runtime/panic.go:920 +0x270
github.com/alice-lg/alice-lg/pkg/api.ExtCommunity.String({0xc0004ce000?, 0x3, 0x2?})
        /src/alice-lg/pkg/api/response.go:224 +0x131
github.com/alice-lg/alice-lg/pkg/api.(*SearchFilters).UpdateCommunitiesFromLookupRoute(0xc000346b70, 0xc00093c180)
        /src/alice-lg/pkg/api/search_filters.go:426 +0x238
github.com/alice-lg/alice-lg/pkg/http.(*Server).apiLookupPrefixGlobal(0xc0000357d0, {0x13c03f0, 0xc0001ac3c0}, 0xc000100700, {0x4d7320?, 0xc000592380?, 0xc17f61888c68d018?})
        /src/alice-lg/pkg/http/api_endpoints_search.go:139 +0xb69
github.com/alice-lg/alice-lg/pkg/http.(*Server).apiRegisterEndpoints.endpoint.func9({0x13bb310?, 0xc0001d0a80}, 0xc000100700, {0x0, 0x0, 0x0})
        /src/alice-lg/pkg/http/api.go:49 +0xa3
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc00033e6c0, {0x13bb310, 0xc0001d0a80}, 0xc000100700)
        /go/pkg/mod/github.com/julienschmidt/httprouter@v1.3.0/router.go:387 +0x7eb
net/http.serverHandler.ServeHTTP({0xc00093ddd0?}, {0x13bb310?, 0xc0001d0a80?}, 0x6?)
        /usr/local/go/src/net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc000418480, {0x13c03b8, 0xc0000354a0})
        /usr/local/go/src/net/http/server.go:2009 +0x5f4
created by net/http.(*Server).Serve in goroutine 14
        /usr/local/go/src/net/http/server.go:3086 +0x5cb
2024/04/15 18:24:22 http: panic serving 10.0.1.3:53138: interface conversion: interface {} is float64, not int
goroutine 5715587 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1868 +0xb9
panic({0xb7d300?, 0xc00093c480?})
        /usr/local/go/src/runtime/panic.go:920 +0x270
github.com/alice-lg/alice-lg/pkg/api.ExtCommunity.String({0xc000342040?, 0x3, 0x2?})
        /src/alice-lg/pkg/api/response.go:224 +0x131
github.com/alice-lg/alice-lg/pkg/api.(*SearchFilters).UpdateCommunitiesFromLookupRoute(0xc000490090, 0xc000984030)
        /src/alice-lg/pkg/api/search_filters.go:426 +0x238
github.com/alice-lg/alice-lg/pkg/http.(*Server).apiLookupPrefixGlobal(0xc0000357d0, {0x13c03f0, 0xc0002041e0}, 0xc0002a6000, {0x4d7320?, 0xc000592480?, 0xc17f61888e486712?})
        /src/alice-lg/pkg/http/api_endpoints_search.go:139 +0xb69
github.com/alice-lg/alice-lg/pkg/http.(*Server).apiRegisterEndpoints.endpoint.func9({0x13bb310?, 0xc00049c8c0}, 0xc0002a6000, {0x0, 0x0, 0x0})
        /src/alice-lg/pkg/http/api.go:49 +0xa3
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc00033e6c0, {0x13bb310, 0xc00049c8c0}, 0xc0002a6000)
        /go/pkg/mod/github.com/julienschmidt/httprouter@v1.3.0/router.go:387 +0x7eb
net/http.serverHandler.ServeHTTP({0xc00093dd70?}, {0x13bb310?, 0xc00049c8c0?}, 0x6?)
        /usr/local/go/src/net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc0004185a0, {0x13c03b8, 0xc0000354a0})
        /usr/local/go/src/net/http/server.go:2009 +0x5f4
created by net/http.(*Server).Serve in goroutine 14
        /usr/local/go/src/net/http/server.go:3086 +0x5cb
```

**Comment by heaveaxy** [comment]
Yes, I have update it too with alice lg.

**Comment by heaveaxy** [comment]
I viewed pages with imported routes manually and found issue described in first message of this topic. Its still something related to large community with number `211609`. No errors logged, just blanking page.

**Comment by heaveaxy** [comment]
I prepared some debug of js code. I found that function `resolveCommunity` receives a nulled `base` argument.
![image](https://github.com/alice-lg/alice-lg/assets/24751685/28cce729-36cf-4488-870e-506411da480b)

Maybe this will lead to some thoughts

**Comment by heaveaxy** [comment]
Is there any news?
