### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by fangeli0935** [alice-lg/alice-lg#14]
Hi guys !

Im trying to install alice on ubuntu 16.04, but I got this message when run make:

make -C client/ client_prod
make[1]: Entering directory '/home/pop/go/src/github.com/alice-lg/alice-lg/client'
Installing dependencies
yarn install
Building alice UI (production)
DISABLE_LOGGING=1 NODE_ENV=production gulp
assert.js:340
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/home/pop/go/src/github.com/alice-lg/alice-lg/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/home/pop/go/src/github.com/alice-lg/alice-lg/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/home/pop/go/src/github.com/alice-lg/alice-lg/client/gulp/tasks/app.js:46:6)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
Makefile:34: recipe for target 'client_prod' failed
make[1]: *** [client_prod] Error 1
make[1]: Leaving directory '/home/pop/go/src/github.com/alice-lg/alice-lg/client'
Makefile:36: recipe for target 'client_prod' failed
make: *** [client_prod] Error 2

Please, can someone help me?

**Comment by mhannig** [comment]
For now i recommend the use of the dockerized frontend build (make -f Makefile.docker client_prod)
