### ISSUE TITLE
panic: runtime error, using goBGP with insecure=true

### ISSUE THREAD

**Issue by dylancmds** [alice-lg/alice-lg#43]
**alice.conf**
```
[server]
listen_http = 127.0.0.1:80
enable_prefix_lookup = true
enable_neighbors_status_refresh = false
asn = 1234

[housekeeping]
interval = 5
force_release_memory = true


[pagination]
routes_filtered_page_size = 250
routes_accepted_page_size = 250
routes_not_exported_page_size = 250

[rpki]
enabled = true

[neighbours_columns]
address = Neighbour
asn = ASN
state = State
Uptime = Uptime
Description = Description
routes_received = Routes Received
routes_filtered = Filtered

[routes_columns]
network = Network
gateway = Gateway
interface = Interface
metric = Metric
bgp.as_path = AS Path

[lookup_columns]
network = Network
gateway = Gateway
neighbour.asn = ASN
neighbour.description = Description
bgp.as_path = AS Path
routeserver.name = RS

[source.debug0]
name = debug0
group = AMS

[source.debug0.gobgp]
host = 127.0.0.1:6060
processing_timeout = 300
```

I have `insecure=true` set as I could not find any solution to TLS issues mentioned in another thread. 
Now I get runtime errors:

```
alice@521a2d4ee8fa:~/go/src/github.com/alice-lg/alice-lg/bin$ sudo ./alice-lg-linux-amd64
2020/10/23 15:25:36 Skipping malformed BGP community:
2020/10/23 15:25:36 Skipping malformed BGP community:
2020/10/23 15:25:36 Skipping malformed BGP community:
        **        ***               Alice 4.2.0
     *****         ***      *
    *  ***          **     ***      Listening on: 127.0.0.1:80
       ***          **      *       Routeservers: 1
      *  **         **
      *  **         **    ***        ****       ***
     *    **        **     ***      * ***  *   * ***
     *    **        **      **     *   ****   *   ***
    *      **       **      **    **         **    ***
    *********       **      **    **         ********
   *        **      **      **    **         *******
   *        **      **      **    **         **
  *****      **     **      **    ***     *  ****    *
 *   ****    ** *   *** *   *** *  *******    *******
*     **      **     ***     ***    *****      *****
*
 **
2020/10/23 15:25:36 Using configuration: /etc/alice-lg/alice.conf
2020/10/23 15:25:36 Starting local routes store
2020/10/23 15:25:36 Routes Store refresh interval set to: 5m0s
2020/10/23 15:25:36 Starting local neighbours store
2020/10/23 15:25:36 Neighbours Store refresh interval set to: 5m0s
2020/10/23 15:25:36 Preparing and installing assets
**panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x90a5d9]**

goroutine 7 [running]:
github.com/alice-lg/alice-lg/backend/sources/gobgp.(*GoBGP).Neighbours(0xc000330
000, 0x0, 0x0, 0x0)
        /home/alice/go/src/github.com/alice-lg/alice-lg/backend/sources/gobgp/so
urce.go:159 +0x259
main.(*NeighboursStore).update(0xc0000ab5c0)
        /home/alice/go/src/github.com/alice-lg/alice-lg/backend/neighbours_store
.go:120 +0x263
main.(*NeighboursStore).init(0xc0000ab5c0)
        /home/alice/go/src/github.com/alice-lg/alice-lg/backend/neighbours_store
.go:73 +0x2b
created by main.(*NeighboursStore).Start
        /home/alice/go/src/github.com/alice-lg/alice-lg/backend/neighbours_store
.go:68 +0xf0
alice@521a2d4ee8fa:~/go/src/github.com/alice-lg/alice-lg/bin$
```

Let me know what other info/outputs I can provide to help.

**Comment by dylancmds** [comment]
Oof, on a whim I changed the source.debug0.gobgp port to 50051 (it's listening on both 6060 and 50051), which fixed it. Closing this.
