### ISSUE TITLE
Not to sure

### ISSUE THREAD

**Issue by deavmi** [alice-lg/alice-lg#75]
I get a build error, because node-sass uses python2 and the print syntax is wrong:

```
deavmi@bababooey:~/Documents/Builds/alice-lg $ make -C client/ client_prod
make: Entering directory '/home/deavmi/Documents/Builds/alice-lg/client'
Installing dependencies
yarn install
yarn install v1.22.11
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error /home/deavmi/Documents/Builds/alice-lg/client/node_modules/node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments: 
Directory: /home/deavmi/Documents/Builds/alice-lg/client/node_modules/node-sass
Output:
Building: /usr/bin/node /home/deavmi/Documents/Builds/alice-lg/client/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/usr/bin/node',
gyp verb cli   '/home/deavmi/Documents/Builds/alice-lg/client/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@14.17.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "/usr/bin/python3" in the PATH
gyp verb `which` succeeded /usr/bin/python3 /usr/bin/python3
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /usr/bin/python3 -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:319:12)
gyp ERR! stack     at ChildProcess.emit (events.js:376:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1055:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
gyp ERR! System Linux 5.13.7-200.fc34.x86_64
gyp ERR! command "/usr/bin/node" "/home/deavmi/Documents/Builds/alice-lg/client/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/deavmi/Documents/Builds/alice-lg/client/node_modules/node-sass
gyp ERR! node -v v14.17.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
make: *** [Makefile:27: deps] Error 1
make: Leaving directory '/home/deavmi/Documents/Builds/alice-lg/client'
```

Have no idea how I'd fix this.

**Comment by annikahannig** [comment]
For now I suggest you use docker / podman...

**Comment by deavmi** [comment]
Awesome

On 28 October 2021 16:07:17 SAST, Annika Hannig ***@***.***> wrote:
>tbh - I'm not too happy about this either.
>Currently I'm doing a lot of refactoring on the backend. After that, the frontend will get an overhaul (migrating to react-scripts, etc..). After that I'm pretty positive it will compile with a nodejs shipped with a vanilla ubuntu for at least a quater of a year!!
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/alice-lg/alice-lg/issues/75#issuecomment-953880090
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
